New scaffolding
suicidesquadpoc/mena-advisor pull request #3
Opened 2019-09-29 17:52 UTC by mmoralesdev

2019-09-29 17:57 UTC, imedgar commented on .gitignore
> +.vscode/
👍

2019-09-29 17:59 UTC, imedgar commented on app/app.js
> +var express = require('express');
We should change "var" keyword to "let"/ "const" (if it's a constant)

2019-09-29 18:05 UTC, imedgar commented on app/coordinates/coordinate-model.js
> +async function selectAllCoordinates(){
Also use arrow functions instead of the function keyword, e.g:

const selectAllCoordinates = async () => {
  // code here
};

2019-09-29 18:06 UTC, imedgar approved these changes
LGTM, minor comments

2019-09-29 18:07 UTC, imedgar requested changes
Change keywords and functions to arrow functions

2019-09-29 18:27 UTC, imedgar approved these changes
LGTM :)

2019-09-30 07:16 UTC, adriangromero approved these changes
nice coding 👍

2019-09-30 08:41 UTC, merged